### ISSUE TITLE
Why not implement IsString type class?

### ISSUE THREAD

**Issue by yihuang** [meiersi/blaze-builder#5]
I've noticed there is a `fromString` in module `Blaze.ByteString.Builder.Char8` , i just wonder why not implement `IsString` type class? that would be convenient with `OverloadedStrings` extension.

**Comment by meiersi** [comment]
I did not implement such an instance on purpose. The problem is that there is more than one interpretation of a `"hello world" :: Builder` literal. Assume that you see such a literal in some code. Would you kow immediatly and without doubt what its semantics are? Would you know what the semantics of `"λ-view" :: Builder` is? I guess not, as there are many possible encodings of a `String` to a sequence of bytes. Due to this ambiguity, I refrained from giving one encoding priority by implementing a corresponding `IsString` instance.

Note that the user can easily import `Data.ByteStringChar8` and write `fromByteString "hello world"` to specify his intent explicitly.
